language: java
jdk:
- openjdk8
cache:
  directories:
  - "~/.m2"
script: mvn -B --global-toolchains travis-maven-toolchain.xml clean package -DskipTests
install:
- 
before_deploy:
- eval "$(ssh-agent -s)"
- mkdir -p -m 700 /tmp/.sourceforge_ssh
- openssl aes-256-cbc -K $encrypted_02bd270643be_key -iv $encrypted_02bd270643be_iv
  -in id_ed25519.enc -out /tmp/.sourceforge_ssh/id_ed25519 -d
- chmod 600 /tmp/.sourceforge_ssh/id_ed25519
- ssh-add /tmp/.sourceforge_ssh/id_ed25519
deploy:
- provider: script
  script: rsync -e ssh -avP --delete $TRAVIS_BUILD_DIR/build/org.eclipse.birt.p2.updatesite/target/
    sa-mueller-dlr@frs.sourceforge.net:/home/frs/project/birt/development/
  on:
    repo: SaMuellerDLR/birt
    branch: development
- provider: script
  script: rsync -e ssh -avP --delete $TRAVIS_BUILD_DIR/build/org.eclipse.birt.p2.updatesite/target/
    sa-mueller-dlr@frs.sourceforge.net:/home/frs/project/birt/release/$TRAVIS_TAG
  on:
    repo: SaMuellerDLR/birt
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_d2f1c71c33a2_key -iv $encrypted_d2f1c71c33a2_iv
  -in id_ed25519.enc -out id_ed25519 -d
env:
  global:
  - secure: FV0LEgQoXKlAezPo5UUjSfYMNIj563wQ8JAZRUlqL3qcP25B1IVYtpXa9Ud7WEbhzCF9ibbLemCuTMaAR1FMX8+rE+qRtQ1x4POstm3waafy/DrG5dLOwa8GxP/vVv6d9P8f8lnR/ocAVstJcvtyVSOQOHP4bWgnfnW1wUD/LkRDEO252gXJt2QXZ9P5gTCeZ/QYiuOhuICexugcmfJJg9CjUUnPQnaKZqKV6qF69z8CzvFdyStwQEaZpyBWH66FKlxZwrjRoZTnDQVfkgIuwTkWD1XkQzYl/F/eNioQlF1hPlXcAAGCTbi9fn5Eb36qunG4TDY9yA+jyMvpeX+Nf1+iXMyXu8PTfjYu0gMZi3gOgw2W5Y7KGBRLUZEBP34qEVpOx41lFBYaupk5og/JgzVPe06NUQ6PQ7zxNZKkfnFwTfYylbdWEzLxzsSYTVirQsOk+fPzsUMTOhHyL5nnm/d23wM3dXfqpdNcrd/Tu/JfX3y1lqPt+m9pcIAZbOxbEvvzjSbO60HOUMUJi6szXtXkawcZzt0ZfNt4P+z2L9cVaWdSrJTNSI+mdEMV+Hm9fiv80C4rTqXqrw6Uu4c/RuK0XpXVDPhgNwdDX5AXQiCCXBBYaQKOQj5ZYWPoo9Ok+JbPbSPzZP2UjKczdXiRuCTm8UWIdpu1iH1hsbYdbHA=
  - secure: lsfuGha5Su74FZtK7Rp4fT6DZV35Dm2ncfCHKrAtoPF12GIhR85m1Uk7YX3dSZ3i+DTOezpEdv2sjIdBeCygeWffsr98b4T2gQEZhJ5urEyWDEoabFg3CLASugXds/gjLIikcLe6hqdTDf94SfB66snXgWHEVeWhzMrj/uVT1LFVluuk8x65NqEk/aIYmcO/V0hJ95jz735lVaJRBhOWaKpRkp3K0HhMmh1UPYTMhyzuk9NtUCnol41V8b+sK1K1IXMhRA37cRoA0+4RTl7GO946XBNPSy7lRRS6u3y23Yn/uDjXwdiYyIPtTBhzQgUpHl6tuSGgmkycGaVql1y4hc6EVes5bEH72bFN3m5QbC091L+QdYiL8RcOtwMVvgu78sl4PJOdSEG5QhBIkdR5yrJ12DneDoAnqZ+YKXvqA7VLnCdoJASigw+HBH97zY9i2LCRbTp98VawnSAj/xUp1Ly1SKYzTlQZkePvhizevuTo1NARiU2I1s6sBZeP1A/J+G+6EvlTxlh0DFufY77BXeWE4CKXq7HE7luToCfFHj7ImJELsuPoQP1nq5HDt8pyOY0M90Fi/vyiMoY8Gszs4pYu01bft9Bjn3Z1LfPs1vd+lRI7xMh0B4oPwrSeO6SF0P7CGeKAlvT4oX2i12J0ykFLQbEzmz2bWxAo69QEkzg=
