language: java
jdk:
  - openjdk8
cache:
  directories:
    - ~/.m2
script: mvn -B --global-toolchains travis-maven-toolchain.xml clean package -DskipTests
install:
  -
before_deploy:
    - eval "$(ssh-agent -s)"
    - mkdir -p -m 700 /tmp/.sourceforge_ssh
    - openssl aes-256-cbc -K $encrypted_02bd270643be_key -iv encrypted_02bd270643be_iv -in id_ed25519.enc -out /tmp/.sourceforge_ssh/id_ed25519 -d
    - chmod 600 /tmp/.sourceforge_ssh/id_ed25519
    - ssh-add /tmp/.sourceforge_ssh/id_ed25519
deploy:
   provider: script
   on:
    repo: SaMuellerDLR/birt
    branch: development
   script: #
    - rsync -e ssh -avP --delete $TRAVIS_BUILD_DIR/build/org.eclipse.birt.p2.updatesite/target/ sa-mueller-dlr@frs.sourceforge.net:/home/frs/project/birt/development/
