language: java
os: linux
dist: xenial

jdk:
- openjdk8

cache:
  directories:
  - "~/.m2"

addons:
# -----------------------------------------------------------
# Make the sourceforge hosts known, thus ssh connections will
# not ask to accept the finger print of the server
# -----------------------------------------------------------
ssh_known_hosts: frs.sourceforge.net

# -----------------------------------------------------------
# Setup the connection to sourceforge
# --------------------------------------------
before_script:
- eval "$(ssh-agent -s)"
- mkdir -p -m 700 /tmp/.sourceforge_ssh
- openssl aes-256-cbc -K $encrypted_d2f1c71c33a2_key -iv $encrypted_d2f1c71c33a2_iv -in id_ed25519.enc -out /tmp/.sourceforge_ssh/id_ed25519 -d
- chmod 600 /tmp/.sourceforge_ssh/id_ed25519
- ssh-add /tmp/.sourceforge_ssh/id_ed25519

# -----------------------------------------------------------
# Perform the actual build.
# The BIRT build uses a toolchain file to identify the jdk.
# It needs to be passed as a parameter to maven.
# -----------------------------------------------------------
script: mvn clean package -B --global-toolchains travis-maven-toolchain.xml -DskipTests

# -----------------------------------------------------------
# Trigger the install phase.
# --------------------------------------------
install:
- true

before_deploy:
# -----------------------------------------------------------
# Update the development tag beforehand
# And send it back to the origin, otherwise travis will 
# apparently perform a git fetch before, and overwrite the
# moved tag back to the previous state.
#------------------------------------------------------------
- |
 if [ $TRAVIS_BRANCH == "development" && $TRAVIS_PULL_REQUEST == "false" ]; then
    git tag -f development_snapshot
    git remote add github-mtd  https://${GITHUB_API_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    git push -f github-mtd development_snapshot
    git remote remove github-mtd
 fii

deploy:
# -----------------------------------------------------------
# Deploy Development p2 snapshot builds.
# --------------------------------------------
- provider: script
  script: rsync -e ssh -avP --delete $TRAVIS_BUILD_DIR/build/org.eclipse.birt.p2updatesite/target/repository/ sa-mueller-dlr@frs.sourceforge.net:/home/frs/project/birt/development/
  on:
    repo: SaMuellerDLR/birt
    branch: development
# -----------------------------------------------------------
# Deploy Release p2 tag builds.
# --------------------------------------------
- provider: script
  script: rsync -e ssh -avP --delete $TRAVIS_BUILD_DIR/build/org.eclipse.birt.p2updatesite/target/repository/ sa-mueller-dlr@frs.sourceforge.net:/home/frs/project/birt/release/$TRAVIS_TAG
  on:
    repo: SaMuellerDLR/birt
    tags: true
# -----------------------------------------------------------
# Deploy Development product snapshot builds.
# --------------------------------------------
- provider: releases
  token: $GITHUB_API_TOKEN
  file_glob: true
  file: 
  - build/birt-packages/birt-report-all-in-one/target/products/*.zip
  name: BIRT Development Build
  release_notes: Development build on latest commit by Travis CI - $TRAVIS_BRANCH ($TRAVIS_COMMIT) - $(date +'%F %T %Z'). This release is subject to constant change.
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    repo: SaMuellerDLR/birt
    branch: development
