language: java
os: linux
dist: xenial
jdk:
- openjdk8
cache:
  directories:
  - "~/.m2"
addons: 
ssh_known_hosts: frs.sourceforge.net
before_script:
- eval "$(ssh-agent -s)"
- mkdir -p -m 700 /tmp/.sourceforge_ssh
- openssl aes-256-cbc -K $encrypted_d2f1c71c33a2_key -iv $encrypted_d2f1c71c33a2_iv
  -in id_ed25519.enc -out /tmp/.sourceforge_ssh/id_ed25519 -d
- chmod 600 /tmp/.sourceforge_ssh/id_ed25519
- ssh-add /tmp/.sourceforge_ssh/id_ed25519
script: mvn clean package -B --global-toolchains travis-maven-toolchain.xml -DskipTests
install:
- true
before_deploy:
- |
  if [ $TRAVIS_BRANCH == "development" && $TRAVIS_PULL_REQUEST == "false" ]; then
     git tag -f development_snapshot
     git remote add github-mtd  https://${GITHUB_API_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
     git push -f github-mtd development_snapshot
     git remote remove github-mtd
  fi
deploy:
  provider: releases
  api_key:
    secure: qqYJjgk+hip+NfRCsnYiN08k+v2wnqONHeNtMrdXmU8r7E7dGpElWX7TN6ttgaIETx7bfxSr05Nsgqzn7kvuxuoevvcu7GvYuRWjR2U69wR6ZfsjdOHpEsZDjjgg3/i1mzSytuLKbbCAsDA58Pyvlz9w8QNk1SOV0SzKlvM6MtuT+jPgOnNV3KoRwI6d7hnNcnqs5vHArCKHHfgi3aDgOHi9ZAyVVn71+wYF/I5qF9OsBTcKrs5tDGksVTJq8peV9nMI9DyxAexEpEufei8nG/nyMx00qytDu0zm9AweKWiyUYQqX8LkLn1P7Z+e46ivczdw+Wdu77kE9+88c83OHzvrQTG7B+jl+5hKbFBdVlNUpScLeTtSXBeSBAbXkCYFiK8flo6mLy/PC3TF75qsgflv4te8uHB5YHyGGeT0tNZHxnHIEorzm9BecvR9X5sOHug72Q5PytkdAXQvjTjerjQrD5ByNVab3D3MLEvJjph8bxCmUQndQ7XGqaor99S7UgqQY8emcM8hS99LGhUHw431JRBtbyXHMRM9OjLPWBuzHscWqn0CDBndf9izD3B7WPiwUEX0+a2hlAm0tgb3k3bTlabpKYTCtedIcn/qMysGk1hO6cMfDx291Or+5ULTH0IH70fWUtvEWISm+asjhBEAlY5rxYfqh6FsWGSVSqI=
  file: x
  on:
    repo: SaMuellerDLR/birt
    branch: feature/task_9-Upload_BIRT_product_to_
  skip_cleanup: 'true'
