language: java
jdk:
- openjdk8
cache:
  directories:
  - "~/.m2"
script: mvn -B --global-toolchains travis-maven-toolchain.xml clean package -DskipTests
install:
- 
before_deploy:
- eval "$(ssh-agent -s)"
- mkdir -p -m 700 /tmp/.sourceforge_ssh
- openssl aes-256-cbc -K $encrypted_d2f1c71c33a2_key -iv $encrypted_d2f1c71c33a2_iv
  -in id_ed25519.enc -out /tmp/.sourceforge_ssh/id_ed25519 -d
- chmod 600 /tmp/.sourceforge_ssh/id_ed25519
- ssh-add /tmp/.sourceforge_ssh/id_ed25519
deploy:
- provider: script
  script: rsync -e ssh -avP --delete $TRAVIS_BUILD_DIR/build/org.eclipse.birt.p2.updatesite/target/
    sa-mueller-dlr@frs.sourceforge.net:/home/frs/project/birt/development/
  on:
    repo: SaMuellerDLR/birt
    branch: development
- provider: script
  script: rsync -e ssh -avP --delete $TRAVIS_BUILD_DIR/build/org.eclipse.birt.p2.updatesite/target/
    sa-mueller-dlr@frs.sourceforge.net:/home/frs/project/birt/release/$TRAVIS_TAG
  on:
    repo: SaMuellerDLR/birt
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_d2f1c71c33a2_key -iv $encrypted_d2f1c71c33a2_iv
  -in id_ed25519.enc -out id_ed25519 -d
